### ISSUE TITLE
WindowsError:[Error 50]

### ISSUE THREAD

**Issue by carterMgj** [debasishm89/OpenXMolar#1]
Hello, when I use your tool, I meet this problem. 
I want to use *.docx to fuzz winword.exe, unfortunately，I meet a error like following：
----------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "OpenXMolar.py", line 321, in <module>
    fz.StartFuzzer()
  File "OpenXMolar.py", line 261, in StartFuzzer
    proc = debug.execv( self.extra_cmd_arg)
  File "C:\install\python27\lib\site-packages\winappdbg\debug.py", line 356, in execv
    return self.execl(lpCmdLine, **kwargs)
  File "C:\install\python27\lib\site-packages\winappdbg\debug.py", line 499, in execl
    aProcess = self.system.start_process(lpCmdLine, **kwargs)
  File "C:\install\python27\lib\site-packages\winappdbg\process.py", line 4258, in start_process
    lpStartupInfo   = lpStartupInfo)
  File "C:\install\python27\lib\site-packages\winappdbg\win32\defines.py", line 279, in __call__
    return fn(*argv, **argd)
  File "C:\install\python27\lib\site-packages\winappdbg\win32\kernel32.py", line 3886, in CreateProcessA
    _CreateProcessA(lpApplicationName, lpCommandLine, lpProcessAttributes, lpThreadAttributes, bool(bInheritHandles), dwCreationFlags, lpEnvironment, lpCurrentDirectory, byref(lpStartupInfo), byref(lpProcessInformation))
  File "C:\install\python27\lib\site-packages\winappdbg\win32\defines.py", line 156, in RaiseIfZero
    raise ctypes.WinError()
WindowsError: [Error 50] 不支持该请求。
-------------------------------------------------------------------------------------------------------------------
I use *.xlsx to fuzz window excel.exe , it got the same problem.......
Hope I can get your help soon. Thanks

**Comment by debasishm89** [comment]
I will investigate and get back!
Thansk,
Debasish

**Comment by debasishm89** [comment]
Can you please let me know your system configuration and Application arch.?
Operating System (Version and Architecture )
The excel.exe process Architecture (x86 / x64 )

**Comment by carterMgj** [comment]
Very thank you.
my operating system is windows10_64bit  and the excel.exe and word.exe are both office2013_64bit
If I change the fuzzed software, use 'C:\Windows\system32\xpsrchvw.exe' to open *.docx , it can work well.

**Comment by debasishm89** [comment]
Hi,
Can you download and install winappdbg from https://github.com/MarioVilas/winappdbg
 in your system first and try to run the app which is causing the problem using winappdbg using following script.


from winappdbg import Debug
def event_handler( event ):
	pass
debug = Debug( my_event_handler, bKillOnExit = True )
try:
	debug.execv( ['your_app.exe'] ) # Start a new process for debugging.
	debug.loop()
finally:
	debug.stop()

I'm not 100% sure if the version of winappdbg shipped with openxmolar fully compatible with win10.
